### ISSUE TITLE
Cannot start demo with npm

### ISSUE THREAD

**Issue by emramos** [jelgblad/angular2-masonry-demo#2]
Hi,

I'm trying to play with the demo with npm, but I'm getting the error message below.
Basically I simply cloned the repository and run:
`npm install`
`npm start`

I'm getting the following error message:
`ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'directoryExists' of undefined
    at Object.getAutomaticTypeDirectiveNames (/Users/emullerramos/masonry_demo/node_modules/typescript/lib/typescript.js:43865:17)
    at State.loadTypesFromConfig (/Users/emullerramos/masonry_demo/node_modules/awesome-typescript-loader/src/host.ts:150:36)
    at new State (/Users/emullerramos/masonry_demo/node_modules/awesome-typescript-loader/src/host.ts:144:14)
    at Object.ensureInstance (/Users/emullerramos/masonry_demo/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/Users/emullerramos/masonry_demo/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/emullerramos/masonry_demo/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main`

Note I'm just starting with npm and masonry, so please ignore if this is a newbie problem :)

**Comment by ymmedia** [comment]
https://github.com/s-panferov/awesome-typescript-loader/issues/228

update  : typescript@2.0.2
